# Configuração Padrão do Upload do TikTok
headless = true
quit_on_end = true

# Experimentando com entradas
valid_path_names = ["path", "filename", "video", "video_path"]
valid_descriptions = ["description", "desc", "caption"]

# Esperas do WebDriver Selenium
implicit_wait = 5 # segundos
explicit_wait = 20 # segundos
uploading_wait = 60 # segundos

# Tempo de espera entre adicionar hashtags
add_hashtag_wait = 5 # segundos
supported_file_types = ["mp4", "mov", "avi", "wmv", "flv", "webm", "mkv", "m4v", "3gp", "3g2", "gif"]
max_description_length = 150 # caracteres

[paths]
main = "https://www.tiktok.com/"
login = "https://www.tiktok.com/login/phone-or-email/email"
upload = "https://www.tiktok.com/tiktokstudio/upload?from=webapp"

[disguising]
user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
[selectors] # Seletores XPATH do Selenium

[selectors.login]
username_field = "//input[@name=\"username\"]"
password_field = "//input[@type=\"password\"]"
login_button = "//button[@type=\"submit\"]"
alert_user_if_failed = true # envia um alerta e espera em vez de falhar
cookie_of_interest = "sessionid" # cookie para verificar se o login foi bem-sucedido

[selectors.upload]
iframe = "//iframe"
split_window = "//button[./div[text()='Not now']]"
upload_video = "//input[@type='file']"
upload_finished = "//div[contains(@class, 'btn-cancel')]"
upload_confirmation = "//div[@title]"
process_confirmation = "//div[contains(@class, 'resolution-label-text')]"
description = "//div[@contenteditable='true']"
visibility = "//div[@class='tiktok-select-selector']"
options = ["Público", "Amigos", "Privado"]
mention_box = "//div[contains(@class, 'mention-list-popover')]"
mention_box_user_id = "//span[contains(@class, 'user-id')]"
comment = "//label[.='Comentário']/following-sibling::div/input"
duet = "//label[.='Dueto']/following-sibling::div/input"
stitch = "//label[.='Edição']/following-sibling::div/input"
post = "//button[@data-e2e='post_video_button']"
post_confirmation = "//div[contains(text(), 'Seu vídeo foi enviado') or contains(text(), '视频已发布') or contains(text(), 'Vídeo publicado')]"

[selectors.schedule]
switch = "//*[@id='tux-1']"
date_picker = "//div[contains(@class, 'date-picker-input')]"
calendar = "//div[contains(@class, 'calendar-wrapper')]"
calendar_month = "//span[contains(@class, 'month-title')]"
calendar_valid_days = "//div[@class='jsx-4172176419 days-wrapper']//span[contains(@class, 'day') and contains(@class, 'valid')]"
calendar_arrows = "//span[contains(@class, 'arrow')]" # primeiro anterior, segundo próximo
time_picker = "//div[contains(@class, 'time-picker-input')]"
time_picker_text = "//div[contains(@class, 'time-picker-input')]/*[1]"
time_picker_container = "//div[@class='tiktok-timepicker-time-picker-container']"
timepicker_hours = "//span[contains(@class, 'tiktok-timepicker-left')]"
timepicker_minutes = "//span[contains(@class, 'tiktok-timepicker-right')]"
[selectors.upload.cookies_banner]
banner = "tiktok-cookie-banner"
button = "div.button-wrapper"